question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "What language does Node.js use?", "correct_answer": "JavaScript",
     "incorrect_answers": ["Java", "Java Source", "Joomla Source Code"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "The programming language &#039;Swift&#039; was created to replace what other programming language?",
     "correct_answer": "Objective-C", "incorrect_answers": ["C#", "Ruby", "C++"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "What is the name of Layer 7 of the OSI model?",
     "correct_answer": "Application",
     "incorrect_answers": ["Session", "Network", "Present"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "What does the &quot;MP&quot; stand for in MP3?",
     "correct_answer": "Moving Picture",
     "incorrect_answers": ["Music Player", "Multi Pass", "Micro Point"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The Windows ME operating system was released in the year 2000.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "What is the most preferred image format used for logos in the Wikimedia database?",
     "correct_answer": ".svg", "incorrect_answers": [".png", ".jpeg", ".gif"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The Windows 7 operating system has six main editions.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
